version: '3.3'

  
services:
  flask:
    image: flask_mysql:latest
    container_name: flask_service
    restart: always
    ports:
      - 5000:5000
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_service
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER : user
      MYSQL_PASSWORD : user
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
